language: csharp
solution: VSharp.sln
install:
  - nuget restore VSharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release VSharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./VSharp.Test/bin/Release/VSharp.Test.dll
